package org.yanhuang.plugins.intellij.exportjar.ui;

import com.intellij.openapi.MnemonicHelper;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.compiler.CompileStatusNotification;
import com.intellij.openapi.compiler.CompilerManager;
import com.intellij.openapi.fileChooser.FileChooser;
import com.intellij.openapi.fileChooser.FileChooserDescriptor;
import com.intellij.openapi.fileChooser.FileChooserDescriptorFactory;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.Messages;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.ui.JBSplitter;
import com.intellij.ui.SeparatorFactory;
import com.intellij.ui.TitledSeparator;
import com.intellij.util.ui.components.BorderLayoutPanel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.yanhuang.plugins.intellij.exportjar.ExportPacker;
import org.yanhuang.plugins.intellij.exportjar.model.ExportOptions;
import org.yanhuang.plugins.intellij.exportjar.model.SettingHistory;
import org.yanhuang.plugins.intellij.exportjar.model.SettingSelectFile;
import org.yanhuang.plugins.intellij.exportjar.model.UISizes;
import org.yanhuang.plugins.intellij.exportjar.settings.HistoryDao;
import org.yanhuang.plugins.intellij.exportjar.utils.CommonUtils;
import org.yanhuang.plugins.intellij.exportjar.utils.Constants;
import org.yanhuang.plugins.intellij.exportjar.utils.MessagesUtils;
import org.yanhuang.plugins.intellij.exportjar.utils.UpgradeManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.List;

import static com.intellij.openapi.ui.Messages.getWarningIcon;
import static com.intellij.openapi.ui.Messages.showErrorDialog;
import static com.intellij.util.ui.JBUI.Panels.simplePanel;
import static javax.swing.BorderFactory.createEmptyBorder;
import static org.yanhuang.plugins.intellij.exportjar.utils.CommonUtils.*;

/**
 * Export jar settings dialog — UI built programmatically (replaces GUI Designer .form).
 * <li><b>Export options JCheckBox names match ExportOptions enum values</b></li>
 */
public class SettingDialog extends DialogWrapper {
	@Nullable
	protected VirtualFile[] selectedFiles;
	protected final Project project;
	private JCheckBox exportJavaFileCheckBox;
	private JCheckBox exportClassFileCheckBox;
	private JCheckBox exportTestFileCheckBox;
	private JCheckBox exportAddDirectoryCheckBox;
	protected JComboBox<String> outPutJarFileComboBox;
	private JButton selectJarFileButton;
	private JPanel settingPanel;
	protected JPanel fileListPanel;
	private JButton debugButton;
	protected JPanel optionsPanel;
	private JPanel jarFilePanel;
	private JBSplitter fileListSettingSplitPanel;
	private JPanel templatePanel;
	protected JCheckBox templateEnableCheckBox;
	protected JComboBox<String> templateSelectComBox;
	protected JButton templateSaveButton;
	protected JButton templateDelButton;
	private JPanel templateTitlePanel;
	private JPanel outputJarTitlePanel;
	private JPanel optionTitlePanel;
	protected FileListDialog fileListDialog;
	private BorderLayoutPanel fileListLabel;
	private final HistoryDao historyDao = new HistoryDao();

	private final TemplateEventHandler templateHandler = new TemplateEventHandler(this);

	public SettingDialog(Project project, @Nullable VirtualFile[] selectedFiles, @Nullable String template) {
		super(true);
		MessagesUtils.getMessageView(project);
		this.project = project;
		this.selectedFiles = selectedFiles;
		buildUI();
		init();
		migrateSavedHistory();
		historyDao.initV2023();
		createFileListTree();
		updateSettingPanelComponents();
		updateComponentState(template);
		updateTemplateUiState();
		this.templateEnableCheckBox.addItemListener(templateHandler::templateEnableChanged);
		this.templateSaveButton.addActionListener(templateHandler::saveTemplate);
		this.templateDelButton.addActionListener(templateHandler::delTemplate);
		this.templateSelectComBox.addItemListener(templateHandler::templateSelectChanged);
		this.outPutJarFileComboBox.addItemListener(templateHandler::exportJarChanged);
		initMnemonics();
	}

	/** Build all Swing components (previously generated by GUI Designer .form). */
	private void buildUI() {
		exportJavaFileCheckBox = new JCheckBox("Export so&urce file");
		exportJavaFileCheckBox.setName("export_java");
		exportJavaFileCheckBox.setSelected(true);

		exportClassFileCheckBox = new JCheckBox("Export &class file");
		exportClassFileCheckBox.setName("export_class");
		exportClassFileCheckBox.setSelected(true);

		exportTestFileCheckBox = new JCheckBox("Export t&est file");
		exportTestFileCheckBox.setName("export_test");

		exportAddDirectoryCheckBox = new JCheckBox("Add d&irectory entries");
		exportAddDirectoryCheckBox.setName("add_directory");

		optionsPanel = new JPanel(new GridLayout(4, 2, 0, 0));
		optionsPanel.add(new JLabel());
		optionsPanel.add(exportJavaFileCheckBox);
		optionsPanel.add(new JLabel());
		optionsPanel.add(exportClassFileCheckBox);
		optionsPanel.add(new JLabel());
		optionsPanel.add(exportTestFileCheckBox);
		optionsPanel.add(new JLabel());
		optionsPanel.add(exportAddDirectoryCheckBox);

		outPutJarFileComboBox = new JComboBox<>();
		outPutJarFileComboBox.setEditable(true);
		selectJarFileButton = new JButton("&Path...");
		selectJarFileButton.setPreferredSize(new Dimension(64, -1));
		selectJarFileButton.setToolTipText("select output jar storage path");
		selectJarFileButton.addActionListener(this::onSelectJarFileButton);
		jarFilePanel = new JPanel(new BorderLayout());
		jarFilePanel.add(outPutJarFileComboBox, BorderLayout.CENTER);
		jarFilePanel.add(selectJarFileButton, BorderLayout.EAST);

		templateEnableCheckBox = new JCheckBox("Te&mplate");
		templateEnableCheckBox.setToolTipText("enable/disable template");
		templateSelectComBox = new JComboBox<>();
		templateSelectComBox.setEditable(true);
		templateSaveButton = new JButton("&Save");
		templateSaveButton.setPreferredSize(new Dimension(48, -1));
		templateDelButton = new JButton("&Del");
		templateDelButton.setPreferredSize(new Dimension(38, -1));
		JPanel templateButtons = new JPanel(new BorderLayout());
		templateButtons.add(templateSaveButton, BorderLayout.WEST);
		templateButtons.add(templateDelButton, BorderLayout.EAST);
		templatePanel = new JPanel(new BorderLayout());
		templatePanel.setToolTipText("Save export files and settings to template");
		templatePanel.add(templateSelectComBox, BorderLayout.CENTER);
		templatePanel.add(templateButtons, BorderLayout.EAST);
		templateTitlePanel = new JPanel(new BorderLayout());
		templateTitlePanel.add(templateEnableCheckBox, BorderLayout.WEST);

		outputJarTitlePanel = new JPanel(new BorderLayout());
		optionTitlePanel = new JPanel(new BorderLayout());

		settingPanel = new JPanel();
		settingPanel.setLayout(new BoxLayout(settingPanel, BoxLayout.Y_AXIS));
		settingPanel.add(templateTitlePanel);
		settingPanel.add(templatePanel);
		settingPanel.add(outputJarTitlePanel);
		settingPanel.add(jarFilePanel);
		settingPanel.add(optionTitlePanel);
		settingPanel.add(optionsPanel);
		settingPanel.add(Box.createVerticalGlue());

		fileListPanel = new JPanel(new BorderLayout());

		fileListSettingSplitPanel = new JBSplitter(false, 0.5f);
		fileListSettingSplitPanel.setShowDividerControls(true);

		debugButton = new JButton("Debug");
		debugButton.setVisible(false);
	}

	private void updateComponentState(String template) {
		this.setResizable(true);
		final SettingHistory history = historyDao.readOrDefault();
		final Dimension splitPanelSize =
				Optional.ofNullable(history.getUi()).map(UISizes::getFileSettingSplitPanel).orElse(Constants.fileListSettingSplitPanelSize);
		final float splitPanelRatio =
				Optional.ofNullable(history.getUi()).map(UISizes::getFileSettingSplitRatio).orElse(0.5f);
		this.fileListSettingSplitPanel.setPreferredSize(splitPanelSize);
		this.fileListSettingSplitPanel.setProportion(splitPanelRatio);
		final Dimension dialogSize =
				Optional.ofNullable(history.getUi()).map(UISizes::getExportDialog).orElse(Constants.settingDialogSize);
		this.setSize(dialogSize.width, dialogSize.height);
		this.templateHandler.initUI(history, template);
	}

	protected void updateTemplateUiState() {
	}

	public JBSplitter getFileListSettingSplitPanel() {
		return fileListSettingSplitPanel;
	}

	protected void createFileListTree() {
		if (this.fileListLabel != null) {
			fileListPanel.remove(fileListLabel);
		}
		if (this.fileListDialog != null) {
			fileListPanel.remove(this.fileListDialog.getCenterPanel());
			disposeFileListDialog();
		}
		this.fileListDialog = createFilesDialog();
		final JComponent selectTreePanel = fileListDialog.getCenterPanel();
		final JPanel separatorPanel = UIFactory.createTitledSeparatorPanel(Constants.titleFileList, selectTreePanel);
		this.fileListLabel = simplePanel(separatorPanel).withBorder(createEmptyBorder());
		this.fileListPanel.add(fileListLabel, BorderLayout.NORTH);
		this.fileListPanel.add(selectTreePanel, BorderLayout.CENTER);
	}

	@NotNull
	private FileListDialog createFilesDialog() {
		final var allVfs = getListFilesInBgt();
		final FileListDialog dialog = new FileListDialog(this.project, List.copyOf(allVfs), null, null, true, false);
		dialog.addFileTreeChangeListener((d, e) -> {
			final Collection<VirtualFile> files = d.getSelectedFiles();
			getOKAction().setEnabled(null != files && !files.isEmpty());
		});
		return dialog;
	}

	private Set<VirtualFile> getListFilesInBgt() {
		return runInBgtWithReadLockAndWait(this::getListFiles, project);
	}

	private Set<VirtualFile> getListFiles() {
		final Set<VirtualFile> allVfs = new HashSet<>();
		for (VirtualFile virtualFile : Optional.ofNullable(this.selectedFiles).orElse(new VirtualFile[0])) {
			CommonUtils.collectExportFilesNest(project, allVfs, virtualFile);
		}
		return allVfs;
	}

	private void updateSettingPanelComponents() {
		createJarOutputPanelTiledSeparator();
		createOptionPanelTitledSeparator();
	}

	private void createJarOutputPanelTiledSeparator() {
		createTitledSeparatorForPanel(this.outputJarTitlePanel, Constants.titleJarFileSeparator, this.outPutJarFileComboBox);
	}

	private void createOptionPanelTitledSeparator() {
		createTitledSeparatorForPanel(this.optionTitlePanel, Constants.titleOptionSeparator, this.optionsPanel);
	}

	private void createTitledSeparatorForPanel(JPanel borderContainer, String title, JComponent separatorForComp) {
		final TitledSeparator separator = SeparatorFactory.createSeparator(title, separatorForComp);
		borderContainer.add(separator, BorderLayout.CENTER);
	}

	private void initMnemonics() {
		MnemonicHelper.init(getContentPane());
	}

	private void migrateSavedHistory() {
		UpgradeManager.migrateHistoryToV2023(this.project);
	}

	public ExportOptions[] pickExportOptions() {
		final Component[] components = optionsPanel.getComponents();
		return Arrays.stream(components).filter(c -> c instanceof JCheckBox)
				.filter(c -> ((JCheckBox) c).isSelected())
				.map(Component::getName)
				.map(String::toLowerCase)
				.filter(n -> {
					try {
						ExportOptions.valueOf(n);
						return true;
					} catch (Exception e) {
						return false;
					}
				}).map(ExportOptions::valueOf).toArray(ExportOptions[]::new);
	}

	private void onSelectJarFileButton(ActionEvent event) {
		FileChooserDescriptor descriptor = FileChooserDescriptorFactory.createSingleFileDescriptor();
		FileChooser.chooseFile(descriptor, project, null, virtualFile -> {
			String filePath = virtualFile.getPath();
			if (!filePath.trim().isEmpty()) {
				((DefaultComboBoxModel<String>) outPutJarFileComboBox.getModel()).insertElementAt(filePath, 0);
				outPutJarFileComboBox.setSelectedIndex(0);
			}
		});
	}

	/** final selected files to export; always not null, possible length=0 */
	public VirtualFile[] getExportingFiles() {
		return fileListDialog.getSelectedFiles().toArray(new VirtualFile[0]);
	}

	public SettingSelectFile[] getIncludeExcludeSelections() {
		return this.fileListDialog.getStoreIncludeExcludeSelections();
	}

	public void onOK() {
		final VirtualFile[] finalSelectFiles = this.getExportingFiles();
		backgroundRunWithoutLock(() -> doExport(finalSelectFiles), project, "Exporting files");
	}

	public void setSelectedFiles(VirtualFile[] selectedFiles) {
		this.selectedFiles = selectedFiles;
		createFileListTree();
	}

	public void setIncludeExcludeSelections(SettingSelectFile[] inExSelectFiles) {
		this.selectedFiles =
				Arrays.stream(inExSelectFiles != null ? inExSelectFiles : new SettingSelectFile[0]).map(SettingSelectFile::getVirtualFile).toArray(VirtualFile[]::new);
		createFileListTree();
		this.fileListDialog.setFlaggedIncludeExcludeSelections(inExSelectFiles);
		this.fileListDialog.getHandler().setShouldUpdateIncludeExclude(true);
	}

	public FileListDialog getFileListDialog() {
		return fileListDialog;
	}

	public void doExport(VirtualFile[] exportFiles) {
		if (isEmpty(exportFiles)) {
			return;
		}
		final var app = ApplicationManager.getApplication();
		final var modules = runInBgtWithReadLockAndWait(() -> findModule(project, exportFiles), project);
		final String selectedOutputJarFullPath = (String) this.outPutJarFileComboBox.getModel().getSelectedItem();
		if (selectedOutputJarFullPath == null || selectedOutputJarFullPath.trim().isEmpty()) {
			app.invokeAndWait(() -> showErrorDialog(project, "The selected output path should not empty",
					Constants.actionName));
			return;
		}
		Path exportJarFullPath = Paths.get(selectedOutputJarFullPath.trim());
		if (!Files.isDirectory(exportJarFullPath)) {
			Path exportJarParentPath = exportJarFullPath.getParent();
			if (exportJarParentPath == null) {
				String basePath = project.getBasePath();
				exportJarParentPath = Paths.get(Objects.requireNonNullElse(basePath, "./"));
				exportJarFullPath = exportJarParentPath.resolve(exportJarFullPath);
			}
			if (!Files.exists(exportJarParentPath)) {
				app.invokeAndWait(() -> showErrorDialog(project, "The selected output path is not exists",
						Constants.actionName));
			} else {
				String exportJarName = exportJarFullPath.getFileName().toString();
				if (!exportJarName.endsWith(".jar")) {
					exportJarFullPath = Paths.get(exportJarFullPath + ".jar");
				}
				if (Files.exists(exportJarFullPath)) {
					final int[] result = new int[1];
					final Path finalJarPath = exportJarFullPath;
					app.invokeAndWait(() -> result[0] = Messages.showYesNoDialog(project, finalJarPath + " already " +
									"exists, replace it? ",
							Constants.actionName, getWarningIcon()));
					if (result[0] == Messages.NO) {
						return;
					}
				}
				this.dispose();
				templateHandler.saveCurTemplate();
				templateHandler.saveGlobalTemplate();
				final CompileStatusNotification packager = new ExportPacker(project, exportFiles, exportJarFullPath,
						pickExportOptions());
				app.invokeAndWait(() -> CompilerManager.getInstance(project).make(project, null == modules ?
						new Module[0] : modules, packager));
			}
		} else {
			app.invokeAndWait(() -> showErrorDialog(project, "Please specify export jar file name",
					Constants.actionName));
		}
	}

	private boolean isEmpty(VirtualFile[] exportFiles) {
		if (exportFiles == null || exportFiles.length == 0) {
			ApplicationManager.getApplication().invokeAndWait(() -> showErrorDialog(project, "Export files is empty, " +
					"please select them first", Constants.actionName));
			return true;
		}
		return false;
	}

	@Override
	protected @Nullable JComponent createCenterPanel() {
		fileListSettingSplitPanel.setFirstComponent(fileListPanel);
		fileListSettingSplitPanel.setSecondComponent(settingPanel);
		return fileListSettingSplitPanel;
	}

	@Override
	protected @NotNull Action[] createActions() {
		return new Action[]{getOKAction(), getCancelAction()};
	}

	@Override
	protected void doOKAction() {
		onOK();
	}

	@Override
	public void dispose() {
		disposeInEdt();
	}

	private void disposeInEdt() {
		ApplicationManager.getApplication().invokeAndWait(() -> {
			disposeFileListDialog();
			super.dispose();
		});
	}

	public UISizes currentUISizes() {
		final UISizes sizes = new UISizes();
		sizes.setExportDialog(this.getSize());
		sizes.setFileSettingSplitPanel(this.fileListSettingSplitPanel.getPreferredSize());
		sizes.setFileSettingSplitRatio(this.fileListSettingSplitPanel.getProportion());
		return sizes;
	}

	private void disposeFileListDialog() {
		if (this.fileListDialog == null || this.fileListDialog.isDisposed()) {
			return;
		}
		final FileListDialog toDispose = this.fileListDialog;
		ApplicationManager.getApplication().invokeLater(() -> toDispose.close(CANCEL_EXIT_CODE));
	}

}
